<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;
use Carbon\Carbon;

class HumanResourcesSeeders extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void {

        $faker = Faker::create();

        DB::table('departments')->insert([
            [
                'department_code' => 'BA',
                'department_desc' => 'Business Audit',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'COR-SEC',
                'department_desc' => 'Corporate Secretary',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'ENM',
                'department_desc' => 'Engineering Maintenance',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'ESH',
                'department_desc' => 'Environment, Safety, and Health',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'YSI',
                'department_desc' => 'Filament 1 Inspection',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'YSL',
                'department_desc' => 'Filament 1 Logistic',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'YSP',
                'department_desc' => 'Filament 1 Proses',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'YSPP',
                'department_desc' => 'Filament 1 Planing Product',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'YSQ',
                'department_desc' => 'Filament 1 Quality Control',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'YOI',
                'department_desc' => 'Filament 2 YO Inspection',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'YOL',
                'department_desc' => 'Filament 2 YO Logistic',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'YOQ',
                'department_desc' => 'Filament 2 YO Qualtiy Control',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'YXI',
                'department_desc' => 'Filament 3 YX Inspection',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'YXL',
                'department_desc' => 'Filament 3 YX Logistic',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'YXQ',
                'department_desc' => 'Filament 3 YX Quality Control',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'FAC',
                'department_desc' => 'Finance & Accounting',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'GA',
                'department_desc' => 'General Affair',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'H',
                'department_desc' => 'HRD Division',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'L',
                'department_desc' => 'HRD Personnel',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'IT',
                'department_desc' => 'Information Technology',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'department_code' => 'M',
                'department_desc' => 'Marketing Division',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
        ]);

        DB::table('jabatans')->insert([
            [
                'jabatan_code'=>'AM',
                'jabatan_desc'=>'ASSISTANT MANAGER',
                'grade_code'=>'MGN',
                'grade_desc'=>'MANAGEMENT',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'DIR',
                'jabatan_desc'=>'DIRECTOR',
                'grade_code'=>'MGN',
                'grade_desc'=>'MANAGEMENT',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'GM',
                'jabatan_desc'=>'GENERAL MANAGER',
                'grade_code'=>'MGN',
                'grade_desc'=>'MANAGEMENT',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'MGR',
                'jabatan_desc'=>'MANAGER',
                'grade_code'=>'MGN',
                'grade_desc'=>'MANAGEMENT',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O1',
                'jabatan_desc'=>'OPERATOR',
                'grade_code'=>'O1-1',
                'grade_desc'=>'JOB O1 GRADE 1',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O1',
                'jabatan_desc'=>'OPERATOR',
                'grade_code'=>'O1-10',
                'grade_desc'=>'JOB O1 GRADE 10',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O1',
                'jabatan_desc'=>'OPERATOR',
                'grade_code'=>'O1-2',
                'grade_desc'=>'JOB O1 GRADE 2',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O1',
                'jabatan_desc'=>'OPERATOR',
                'grade_code'=>'O1-3',
                'grade_desc'=>'JOB O1 GRADE 3',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O1',
                'jabatan_desc'=>'OPERATOR',
                'grade_code'=>'O1-4',
                'grade_desc'=>'JOB O1 GRADE 4',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O1',
                'jabatan_desc'=>'OPERATOR',
                'grade_code'=>'O1-5',
                'grade_desc'=>'JOB O1 GRADE 5',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O1',
                'jabatan_desc'=>'OPERATOR',
                'grade_code'=>'O1-6',
                'grade_desc'=>'JOB O1 GRADE 6',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O1',
                'jabatan_desc'=>'OPERATOR',
                'grade_code'=>'O1-7',
                'grade_desc'=>'JOB O1 GRADE 7',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O1',
                'jabatan_desc'=>'OPERATOR',
                'grade_code'=>'O1-8',
                'grade_desc'=>'JOB O1 GRADE 8',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O1',
                'jabatan_desc'=>'OPERATOR',
                'grade_code'=>'O1-9',
                'grade_desc'=>'JOB O1 GRADE 9',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O2',
                'jabatan_desc'=>'OPERATOR LEADER',
                'grade_code'=>'O2-1',
                'grade_desc'=>'JOB O2 GRADE 1',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O2',
                'jabatan_desc'=>'OPERATOR LEADER',
                'grade_code'=>'O2-2',
                'grade_desc'=>'JOB O2 GRADE 2',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O2',
                'jabatan_desc'=>'OPERATOR LEADER',
                'grade_code'=>'O2-3',
                'grade_desc'=>'JOB O2 GRADE 3',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O2',
                'jabatan_desc'=>'OPERATOR LEADER',
                'grade_code'=>'O2-4',
                'grade_desc'=>'JOB O2 GRADE 4',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O2',
                'jabatan_desc'=>'OPERATOR LEADER',
                'grade_code'=>'O2-5',
                'grade_desc'=>'JOB O2 GRADE 5',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O2',
                'jabatan_desc'=>'OPERATOR LEADER',
                'grade_code'=>'O2-6',
                'grade_desc'=>'JOB O2 GRADE 6',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O2',
                'jabatan_desc'=>'OPERATOR LEADER',
                'grade_code'=>'O2-7',
                'grade_desc'=>'JOB O2 GRADE 7',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O2',
                'jabatan_desc'=>'OPERATOR LEADER',
                'grade_code'=>'O2-8',
                'grade_desc'=>'JOB O2 GRADE 8',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O2',
                'jabatan_desc'=>'OPERATOR LEADER',
                'grade_code'=>'O2-9',
                'grade_desc'=>'JOB O2 GRADE 9',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'O2',
                'jabatan_desc'=>'OPERATOR LEADER',
                'grade_code'=>'O2-10',
                'grade_desc'=>'JOB O2 GRADE 10',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'PD',
                'jabatan_desc'=>'PRESIDENT DIRECTOR',
                'grade_code'=>'MGN',
                'grade_desc'=>'MANAGEMENT',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S1',
                'jabatan_desc'=>'SUPERVISOR',
                'grade_code'=>'S1-1',
                'grade_desc'=>'JOB S1 GRADE 1',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S1',
                'jabatan_desc'=>'SUPERVISOR',
                'grade_code'=>'S1-2',
                'grade_desc'=>'JOB S1 GRADE 2',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S1',
                'jabatan_desc'=>'SUPERVISOR',
                'grade_code'=>'S1-3',
                'grade_desc'=>'JOB S1 GRADE 3',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S1',
                'jabatan_desc'=>'SUPERVISOR',
                'grade_code'=>'S1-4',
                'grade_desc'=>'JOB S1 GRADE 4',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S1',
                'jabatan_desc'=>'SUPERVISOR',
                'grade_code'=>'S1-5',
                'grade_desc'=>'JOB S1 GRADE 5',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S1',
                'jabatan_desc'=>'SUPERVISOR',
                'grade_code'=>'S1-6',
                'grade_desc'=>'JOB S1 GRADE 6',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S1',
                'jabatan_desc'=>'SUPERVISOR',
                'grade_code'=>'S1-7',
                'grade_desc'=>'JOB S1 GRADE 7',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S1',
                'jabatan_desc'=>'SUPERVISOR',
                'grade_code'=>'S1-8',
                'grade_desc'=>'JOB S1 GRADE 8',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S1',
                'jabatan_desc'=>'SUPERVISOR',
                'grade_code'=>'S1-9',
                'grade_desc'=>'JOB S1 GRADE 9',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S1',
                'jabatan_desc'=>'SUPERVISOR',
                'grade_code'=>'S1-10',
                'grade_desc'=>'JOB S1 GRADE 10',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S2',
                'jabatan_desc'=>'SUPERINTENDENT',
                'grade_code'=>'S2-1',
                'grade_desc'=>'JOB S2 GRADE 1',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S2',
                'jabatan_desc'=>'SUPERINTENDENT',
                'grade_code'=>'S2-2',
                'grade_desc'=>'JOB S2 GRADE 2',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S2',
                'jabatan_desc'=>'SUPERINTENDENT',
                'grade_code'=>'S2-3',
                'grade_desc'=>'JOB S2 GRADE 3',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S2',
                'jabatan_desc'=>'SUPERINTENDENT',
                'grade_code'=>'S2-4',
                'grade_desc'=>'JOB S2 GRADE 4',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S2',
                'jabatan_desc'=>'SUPERINTENDENT',
                'grade_code'=>'S2-5',
                'grade_desc'=>'JOB S2 GRADE 5',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S2',
                'jabatan_desc'=>'SUPERINTENDENT',
                'grade_code'=>'S2-6',
                'grade_desc'=>'JOB S2 GRADE 6',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
            [
                'jabatan_code'=>'S2',
                'jabatan_desc'=>'SUPERINTENDENT',
                'grade_code'=>'S2-7',
                'grade_desc'=>'JOB S2 GRADE 7',
                'status'=>true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now(),
            ],
        ]);
        DB::table('categories')->insert([
            [
                'calgrp_code' => '4/1S1',
                'calgrp_desc' => '4/1S1',
                'work_code' => 'S4/1',
                'work_desc' => 'Shift 4/1',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => '4/1S2',
                'calgrp_desc' => '4/1S2',
                'work_code' => 'S4/1',
                'work_desc' => 'Shift 4/1',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => '4/1S3',
                'calgrp_desc' => '4/1S3',
                'work_code' => 'S4/1',
                'work_desc' => 'Shift 4/1',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => '4/1S4',
                'calgrp_desc' => '4/1S4',
                'work_code' => 'S4/1',
                'work_desc' => 'Shift 4/1',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => '5/1D1',
                'calgrp_desc' => '5/1D1',
                'work_code' => 'D5/1',
                'work_desc' => 'Daily 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => '5/1D2',
                'calgrp_desc' => '5/1D2',
                'work_code' => 'D5/1',
                'work_desc' => 'Daily 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => '5/1D3',
                'calgrp_desc' => '5/1D3',
                'work_code' => 'D5/1',
                'work_desc' => 'Daily 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => '5/1D4',
                'calgrp_desc' => '5/1D4',
                'work_code' => 'D5/1',
                'work_desc' => 'Daily 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => '5/1D5',
                'calgrp_desc' => '5/1D5',
                'work_code' => 'D5/1',
                'work_desc' => 'Daily 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => '5/1D6',
                'calgrp_desc' => '5/1D6',
                'work_code' => 'D5/1',
                'work_desc' => 'Daily 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'A1 QARD-5/1 2S',
                'calgrp_desc' => 'A1 QARD-5/1 2S',
                'work_code' => 'QARD-S5/1',
                'work_desc' => 'QARD SHIFT 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'A2 PASO QARD-5/1 2S',
                'calgrp_desc' => 'A2 PASO QARD-5/1 2S',
                'work_code' => 'SHIFT 5/1 PASO',
                'work_desc' => 'SHIFT 5/1 PASO',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'A2 QARD-5/1Â 2S',
                'calgrp_desc' => 'A2 QARD-5/1Â 2S',
                'work_code' => 'QARD-S5/1',
                'work_desc' => 'QARD SHIFT 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'B1 PASO QARD-5/1 2S',
                'calgrp_desc' => 'B1 PASO QARD-5/1 2S',
                'work_code' => 'SHIFT 5/1 PASO',
                'work_desc' => 'SHIFT 5/1 PASO',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'B1 QARD-5/1 2S',
                'calgrp_desc' => 'B1 QARD-5/1 2S',
                'work_code' => 'QARD-S5/1',
                'work_desc' => 'QARD SHIFT 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'B2 QARD-5/1Â 2S',
                'calgrp_desc' => 'B2 QARD-5/1Â 2S',
                'work_code' => 'QARD-S5/1',
                'work_desc' => 'QARD SHIFT 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'C1 PASO QARD-5/1 2S',
                'calgrp_desc' => 'C1 PASO QARD-5/1 2S',
                'work_code' => 'SHIFT 5/1 PASO',
                'work_desc' => 'SHIFT 5/1 PASO',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'C1 QARD-5/1 2S',
                'calgrp_desc' => 'C1 QARD-5/1 2S',
                'work_code' => 'QARD-S5/1',
                'work_desc' => 'QARD SHIFT 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'C2 PASO QARD-5/1 2S',
                'calgrp_desc' => 'C2 PASO QARD-5/1 2S',
                'work_code' => 'SHIFT 5/1 PASO',
                'work_desc' => 'SHIFT 5/1 PASO',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'C2 QARD-5/1Â 2S',
                'calgrp_desc' => 'C2 QARD-5/1Â 2S',
                'work_code' => 'QARD-S5/1',
                'work_desc' => 'QARD SHIFT 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'D1 PASO QARD-5/1 2S',
                'calgrp_desc' => 'D1 PASO QARD-5/1 2S',
                'work_code' => 'SHIFT 5/1 PASO',
                'work_desc' => 'SHIFT 5/1 PASO',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'D1 QARD-5/1 2S',
                'calgrp_desc' => 'D1 QARD-5/1 2S',
                'work_code' => 'QARD-S5/1',
                'work_desc' => 'QARD SHIFT 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'D2 PASO QARD-5/1 2S',
                'calgrp_desc' => 'D2 PASO QARD-5/1 2S',
                'work_code' => 'SHIFT 5/1 PASO',
                'work_desc' => 'SHIFT 5/1 PASO',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'D5/2 06001430 v1',
                'calgrp_desc' => 'D5/2 0600-1430 HR/GA',
                'work_code' => 'D5/2 0600-1430',
                'work_desc' => 'Daily 5/2 0600-1430',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'D5/2 MKTD-FY P',
                'calgrp_desc' => 'Marketing Warehouse FY Pagi',
                'work_code' => 'D5/2 MKT PASI(08:00)',
                'work_desc' => 'Daily Shift (08:00-16:30 & 13:00-21:30)',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'D5/2 MKTD-FY SIPA',
                'calgrp_desc' => 'D5/2 MKTD-FY SIPA',
                'work_code' => 'D5/2 MKT SIPA(13:00)',
                'work_desc' => 'Daily Shift ( 13:00-21:30 & 08:00-16:30  )',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'D5/2 MKTD-SF PASO',
                'calgrp_desc' => 'D5/2 MKTD-SF PASO',
                'work_code' => 'D5/2 MKT PASO(08:00)',
                'work_desc' => 'Daily Shift ( 08:00-16:30 & 16:30-01:00 )',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'D5/2 MKTD-SF SOPA',
                'calgrp_desc' => 'D5/2 MKTD-SF SOPA',
                'work_code' => 'D5/2 MKT SOPA(16:30)',
                'work_desc' => 'Daily Shift (16:30-01:00 & 08:00-16:30)',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'DAILY',
                'calgrp_desc' => 'DAILY',
                'work_code' => 'D5/2',
                'work_desc' => 'Daily 5/2',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'E1 PASO QARD-5/1 2S',
                'calgrp_desc' => 'E1 PASO QARD-5/1 2S',
                'work_code' => 'SHIFT 5/1 PASO',
                'work_desc' => 'SHIFT 5/1 PASO',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'E2 PASO QARD-5/1 2S',
                'calgrp_desc' => 'E2 PASO QARD-5/1 2S',
                'work_code' => 'SHIFT 5/1 PASO',
                'work_desc' => 'SHIFT 5/1 PASO',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'E2 QARD-5/1Â 2S',
                'calgrp_desc' => 'E2 QARD-5/1Â 2S',
                'work_code' => 'QARD-S5/1',
                'work_desc' => 'QARD SHIFT 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'F1 PASO QARD-5/1 2S',
                'calgrp_desc' => 'F1 PASO QARD-5/1 2S',
                'work_code' => 'SHIFT 5/1 PASO',
                'work_desc' => 'SHIFT 5/1 PASO',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'GA 5/1D2 (JAM 6)',
                'calgrp_desc' => 'GA 5/1D2 (JAM 6)',
                'work_code' => 'HRDGA D5/1 0614',
                'work_desc' => 'HRDGA D5/1 0614',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'GA 5/1D3 (JAM 6)',
                'calgrp_desc' => 'GA 5/1D3 (JAM 6)',
                'work_code' => 'HRDGA D5/1 0614',
                'work_desc' => 'HRDGA D5/1 0614',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'GA 5/1D6 (JAM 6)',
                'calgrp_desc' => 'GA 5/1D6 (JAM 6)',
                'work_code' => 'HRDGA D5/1 0614',
                'work_desc' => 'HRDGA D5/1 0614',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI D 4 SHIF G1',
                'calgrp_desc' => 'IKI D 4 SHIF G1',
                'work_code' => 'IKI D 4 SHIF',
                'work_desc' => 'IKI D 4 SHIF',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI D 4 SHIF G2',
                'calgrp_desc' => 'IKI D 4 SHIF G2',
                'work_code' => 'IKI D 4 SHIF',
                'work_desc' => 'IKI D 4 SHIF',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI D 4 SHIF G4',
                'calgrp_desc' => 'IKI D 4 SHIF G4',
                'work_code' => 'IKI D 4 SHIF',
                'work_desc' => 'IKI D 4 SHIF',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI D2  G1',
                'calgrp_desc' => 'IKI D2  G1',
                'work_code' => 'IKI D2 SHIFT',
                'work_desc' => 'IKI D2 SHIFT',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI DTY WH SHIFT G1',
                'calgrp_desc' => 'IKI DTY WH SHIFT G1',
                'work_code' => 'IKI DTY WH SHIFT',
                'work_desc' => 'IKI DTY WH SHIFT',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI FOY WH SHIFT G2',
                'calgrp_desc' => 'IKI FOY WH SHIFT G2',
                'work_code' => 'IKI FOY WH SHIFT',
                'work_desc' => 'IKI FOY WH SHIFT',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI FOY WH SHIFT GI',
                'calgrp_desc' => 'IKI FOY WH SHIFT G1',
                'work_code' => 'IKI FOY WH SHIFT',
                'work_desc' => 'IKI FOY WH SHIFT',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI-5/1D1',
                'calgrp_desc' => 'IKI-5/1GR-A',
                'work_code' => 'IKI-D5/1',
                'work_desc' => 'IKI Daily 5/1',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI-5/1D2',
                'calgrp_desc' => 'IKI-5/1GR-B',
                'work_code' => 'IKI-D5/1',
                'work_desc' => 'IKI Daily 5/1',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI-5/1D3',
                'calgrp_desc' => 'IKI-5/1GR-C',
                'work_code' => 'IKI-D5/1',
                'work_desc' => 'IKI Daily 5/1',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI-5/1D4',
                'calgrp_desc' => 'IKI-5/1GR-D',
                'work_code' => 'IKI-D5/1',
                'work_desc' => 'IKI Daily 5/1',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI-5/1D5',
                'calgrp_desc' => 'IKI-5/1GR-E',
                'work_code' => 'IKI-D5/1',
                'work_desc' => 'IKI Daily 5/1',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI-5/1D6',
                'calgrp_desc' => 'IKI-5/1GR-F',
                'work_code' => 'IKI-D5/1',
                'work_desc' => 'IKI Daily 5/1',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI-5/1S2B',
                'calgrp_desc' => 'SHIFT 5/1 GROUP 2B',
                'work_code' => 'IKI-S5/1',
                'work_desc' => 'IKI SHIFT 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI-5/1S3A',
                'calgrp_desc' => 'SHIFT 5/1 GROUP 3A',
                'work_code' => 'IKI-S5/1',
                'work_desc' => 'IKI SHIFT 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI-5/1S3B',
                'calgrp_desc' => 'SHIFT 5/1 GROUP 3B',
                'work_code' => 'IKI-S5/1',
                'work_desc' => 'IKI SHIFT 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI-5/1S4A',
                'calgrp_desc' => 'SHIFT 5/1 GROUP 4A',
                'work_code' => 'IKI-S5/1',
                'work_desc' => 'IKI SHIFT 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI-5/1S6B',
                'calgrp_desc' => 'SHIFT 5/1 GROUP 6B',
                'work_code' => 'IKI-S5/1',
                'work_desc' => 'IKI SHIFT 5/1',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI-D5/2P',
                'calgrp_desc' => 'Daily 5/2 Pagi',
                'work_code' => 'IKI-D5/2',
                'work_desc' => 'IKI Daily 5/2',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'IKI-D5/2S',
                'calgrp_desc' => 'Daily 5/2 Sore',
                'work_code' => 'IKI-D5/2',
                'work_desc' => 'IKI Daily 5/2',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'SF D/2S G1',
                'calgrp_desc' => 'SF D/2S G1',
                'work_code' => 'SF D/2S',
                'work_desc' => 'SF D/2S',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'SF D/2S G2',
                'calgrp_desc' => 'SF D/2S G2',
                'work_code' => 'SF D/2S',
                'work_desc' => 'SF D/2S',
                'workdayweek' => '5',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'TFC-5/1GR2',
                'calgrp_desc' => 'SHIFT 5/1 GR 2',
                'work_code' => 'TFC-S5/1',
                'work_desc' => 'TFC SHIFT 5/1',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'TFC-5/1GR3',
                'calgrp_desc' => 'SHIFT 5/1 GR 3',
                'work_code' => 'TFC-S5/1',
                'work_desc' => 'TFC SHIFT 5/1',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'calgrp_code' => 'TFC-5/1GR4',
                'calgrp_desc' => 'SHIFT 5/1 GR 4',
                'work_code' => 'TFC-S5/1',
                'work_desc' => 'TFC SHIFT 5/1',
                'workdayweek' => '7',
                'workdayhour' => '0',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

    }
}
